#!/usr/bin/python

import sys
import doi

for c in doi.get_all_collections():
    if not c.doi:
        continue
    if c.doi.record_exists():
        continue
    print 'untagging collection %s (%s)' % (c.id, c.doi.identifier)
    c.untag()

sys.exit(0)

# eof
