#!/usr/bin/python

import sys
import json
import doi
import info

test_flag = True

base_lp_url = 'http://doi.virtualbrain.org'

def create(md):
    """mint the DOI and update the landing page"""
    d = doi.DOI(doi.mint(base_lp_url, md, test_flag))
    d.update_landing_page('%s/lp/%s' % (base_lp_url, d.identifier))
    return d

def anat_url(project, id):
    url = 'http://doi.virtualbrain.org/xnat/app/action/'
    url += 'DisplayItemAction/search_element/'
    url += 'xnat%3AmrSessionData/search_field/'
    url += 'xnat%3AmrSessionData.ID/search_value/'
    url += id
    url += '/popup/false/project/'
    url += project
    return url

def seg_url(project, id):
    url = 'http://doi.virtualbrain.org/xnat/app/action/'
    url += 'DisplayItemAction/search_element/'
    url += 'ir%3ACandiShareSegData/search_field/'
    url += 'ir%3ACandiShareSegData.ID/search_value/'
    url += id
    url += '/popup/false/project/'
    url += project
    return url

def create_images(project_code, project_name, project_doi, image_iterator):
    images = []
    for image_info in image_iterator():
        md = {}
        for key in ('creators', 
                    'publisher', 
                    'publicationyear', 
                    'version', 
                    'rights', 
                    'geolocation'):
            if key in project_doi.metadata:
                md[key] = project_doi.metadata[key]
        if image_info['Type'] == 'Anatomical MR':
            md['resourcetype'] = 'Image/Structural MR'
            url = anat_url(project_code, image_info['XNAT ID'])
        elif image_info['Type'] == 'Manual Segmentation':
            md['resourcetype'] = 'Image/Manual Segmentation'
            url = seg_url(project_code, image_info['XNAT ID'])
        else:
            assert False
        md['alternateidentifiers'] = (('URL', url), )
        md['sizes'] = image_info['Sizes']
        md['formats'] = ('NIfTI-1', )
        md['title'] = '%s for %s subject %s' % (image_info['Type'], 
                                                project_name, 
                                                image_info['Subject'])
        md['relatedidentifiers'] = ((project_doi.identifier, 
                                     'DOI', 
                                     'IsPartOf'), )
        image = create(md)
        print '    image:', image.identifier
        images.append(image)
    md = project_doi.copy_metadata()
    if 'relatedidentifiers' not in md:
        md['relatedidentifiers'] = []
    for image in images:
        md['relatedidentifiers'].append((image.identifier, 'DOI', 'HasPart'))
    project_doi.update_metadata(md)
    print 'updated %s with images' % project_code

candi_share_md = json.load(open('candi_share.json'))
candi_share = create(candi_share_md)
print 'created CANDI Share:', candi_share.identifier

ibsr_md = json.load(open('ibsr.json'))
ibsr = create(ibsr_md)
print 'created IBSR:', ibsr.identifier

create_images('ibsr', 'IBSR', ibsr, info.iteribsr)
create_images('cs_schizbull08', 
              'CANDI Share Schizophrenia Bulletin 2008', 
              candi_share, 
              info.itercs)

sys.exit(0)

# eof
